add task solution
mate-academy/Potr_Pots pull request #160
Opened 2023-10-08 14:08 UTC by NasyTheSlayer

[DEMO LINK](https://NasyTheSlayer.github.io/Potr_Pots/)

2023-10-08 14:21 UTC, anastasiiavorobiova requested changes
Wonderful work! 
<img width="1042" alt="Screenshot 2023-10-08 at 17 13 34" src="https://github.com/mate-academy/Potr_Pots/assets/135232001/4e88795e-52d1-40ee-9d9b-3bc86285c166">
These validation errors should be fixed
<img width="559" alt="Screenshot 2023-10-08 at 17 18 33" src="https://github.com/mate-academy/Potr_Pots/assets/135232001/016cdda4-700a-469d-82cc-3b0b940ef35e">
<img width="647" alt="Screenshot 2023-10-08 at 17 19 20" src="https://github.com/mate-academy/Potr_Pots/assets/135232001/1274bb35-21b3-43f5-a95f-18e09fc13dd3">
Consider making the background span the full width of the screen

2023-10-09 06:10 UTC, volodymyr-soltys97 requested changes
Need to make a deploy
<img width="885" alt="image" src="https://github.com/mate-academy/Potr_Pots/assets/64750958/356a2ebc-486d-4bcf-b601-a09a26fd176f">

2023-10-09 09:33 UTC, VitaliyBondarenko1982 requested changes
Good job.
Sugest a couple improvements.
Fix default [autocomplete styles](https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/) and [make custom scrollbar](https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp) for textarea

2023-10-09 10:22 UTC, anastasiiavorobiova approved these changes
Awesome work!

2025-02-03 13:36 UTC, closed without merging