Potr Pots
mate-academy/Potr_Pots pull request #88
Opened 2022-09-05 15:58 UTC by xiimiik

[DEMO LINK](https://xiimiik.github.io/Potr_Pots/)

2022-09-06 12:19 UTC, Anna-Tkachenko requested changes
Good job!
Some comments:
1) Check the title for the page (POST -> POTS)
2) Don't forget to add some styles on hover state for navigation links
3) Add some styles on hover state for bag icon in header
4) Add some styles on hover state for images in `For Whom` section
5) Fix it
<img width="268" alt="image" src="https://user-images.githubusercontent.com/30314756/188633355-0548150c-7a73-43a2-9f08-586244e12de3.png">

2022-09-06 14:09 UTC, xiimiik commented
> Good job! Some comments:
> 
> 1. Check the title for the page (POST -> POTS)
> 2. Don't forget to add some styles on hover state for navigation links
> 3. Add some styles on hover state for bag icon in header
> 4. Add some styles on hover state for images in `For Whom` section
> 5. Fix it
> 
> <img alt="image" width="268" src="https://user-images.githubusercontent.com/30314756/188633355-0548150c-7a73-43a2-9f08-586244e12de3.png">

Is it a good practice to do amimations at the end? They are distracting me from layout))

2022-09-09 10:27 UTC, Anna-Tkachenko requested changes
Some comments:
1) Awesome effects for images!
2) Page shouldn't be reloaded on form submitting
3) Social icons in footer should be the links on social networks
4) Address in footer should be the link on google maps

2022-09-09 12:41 UTC, Anna-Tkachenko approved these changes
Well Done! ⭐️

2026-07-08 06:18 UTC, closed without merging